version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 0ad-tool
    restart: unless-stopped
    ports:
      - "8080:8081"
    volumes:
      - ./public:/app/public:ro